package com.ems.actions;

import java.util.List;
import java.util.Map;

import com.ems.model.OrganizerEventSummary;
import com.ems.service.OrganizerService;
import com.ems.util.ApplicationUtil;

/**
 * Action class for organizer report and analytics operations.
 * Delegates business logic to appropriate services.
 */
public class OrganizerReportAction {

    private final OrganizerService organizerService;

    public OrganizerReportAction() {
        this.organizerService = ApplicationUtil.organizerService();
    }

    /**
     * Gets event-wise registration summary for an organizer.
     * 
     * @param organizerId the ID of the organizer
     * @return list of maps containing event name and registration count
     */
    public List<Map<String, Object>> getEventWiseRegistrations(int organizerId) {
        return organizerService.getEventWiseRegistrations(organizerId);
    }

    /**
     * Gets ticket sales summary for an organizer.
     * 
     * @param organizerId the ID of the organizer
     * @return list of maps containing ticket type and number sold
     */
    public List<Map<String, Object>> getTicketSales(int organizerId) {
        return organizerService.getTicketSales(organizerId);
    }

    /**
     * Gets the total revenue generated by an organizer across all events.
     * 
     * @param organizerId the ID of the organizer
     * @return the total revenue amount
     */
    public double getRevenueSummary(int organizerId) {
        return organizerService.getRevenueSummary(organizerId);
    }

    /**
     * Gets a comprehensive summary of all events created by an organizer.
     * 
     * @param organizerId the ID of the organizer
     * @return list of organizer event summaries
     */
    public List<OrganizerEventSummary> getOrganizerEventSummary(int organizerId) {
        return organizerService.getOrganizerEventSummary(organizerId);
    }
}
